name: github pages

on:
  push:
    branches:
      - main
      - feature/nimibook-branch2

jobs:
  api-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          # - windows-latest
          # - macOS-latest
        nim:
          - '1.6.10'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}

      - run: nimble install -Y
      - name: Setup dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libgtk-4-dev libadwaita-1-dev

      - name: Build nimibook docs
        run: nimble --verbose genBook

      - name: Archive API docs
        uses: actions/upload-artifact@v3
        with:
          name: api-docs
          path: |
            compiledBook

  deploy-docs:
    needs:
      - api-docs
    runs-on: ubuntu-22.04
    steps:
      - name: Download all docs
        uses: actions/download-artifact@v3

      - name: Check files
        run: |
          find .

      - name: Setup docs
        run: |
          ls api-docs/
          mv api-docs/ docs/

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
